const {test, expect} = require("@playwright/test");
const {readFile} = require("node:fs/promises");
test("drawbridge moves continuously through edge-on with fixed hinges and attached chains", async ({page}) => {
  await page.setContent(await readFile("web/drawbridge-loader.svg", "utf8"));
  const motion = await page.evaluate(() => {
    const svg = document.querySelector("svg");
    svg.pauseAnimations();
    const animations = document.getAnimations();
    animations.forEach(animation => animation.pause());
    let hingeError = 0, chainError = 0, biggestStep = 0, previous;
    for (let frame = 0; frame <= 240; frame++) {
      const time = frame / 60;
      svg.setCurrentTime(time);
      animations.forEach(animation => { animation.currentTime = time * 1000; });
      const matrix = document.querySelector("#bridge-texture").getCTM();
      const project = (x, y) => new DOMPoint(x, y).matrixTransform(matrix);
      for (const [x,y] of [[54,77],[74,85]]) {
        const point = project(x,y);
        hingeError = Math.max(hingeError, Math.hypot(point.x-x,point.y-y));
      }
      const tip = project(44,60), chain = document.querySelector("line");
      chainError = Math.max(chainError, Math.hypot(tip.x-chain.x2.animVal.value, tip.y-chain.y2.animVal.value));
      if (previous) biggestStep = Math.max(biggestStep, Math.hypot(tip.x-previous.x,tip.y-previous.y));
      previous = tip;
    }
    return {hingeError,chainError,biggestStep};
  });
  expect(motion.hingeError).toBeLessThan(.01);
  expect(motion.chainError).toBeLessThan(.03);
  expect(motion.biggestStep).toBeGreaterThan(.1);
  expect(motion.biggestStep).toBeLessThan(1);
});
test("startup errors stay visible instead of leaving a blank page", async ({page}) => {
  await page.addInitScript(() => { window.__scenario = "startup-failure"; });
  await page.goto("/");
  const message = page.locator("#user-state");
  await expect(message).toHaveText("Secure connection couldn't start. Reconnect and reload.");
  await expect(message).toBeInViewport();
  await expect(page.locator("#controls")).toBeHidden();
});
test("centered drawbridge loader animates while securely connecting and loading devices", async ({page}) => {
  await page.addInitScript(() => { window.__scenario = "loading"; });
  await page.goto("/");
  const loader = page.locator("#loading-state");
  await expect(loader).toBeVisible();
  await expect(page.locator("#loading-message")).toHaveText("Securely Connecting");
  const icon = page.locator(".drawbridge-loader img");
  await expect.poll(() => icon.evaluate(image => image.complete && image.naturalWidth === 128)).toBe(true);
  const firstFrame = await icon.screenshot();
  await page.waitForTimeout(550);
  expect((await icon.screenshot()).equals(firstFrame)).toBe(false);
  const aligned = await page.evaluate(() => {
    const icon = document.querySelector(".drawbridge-loader").getBoundingClientRect();
    const text = document.querySelector("#loading-message").getBoundingClientRect();
    return Math.abs(icon.x + icon.width / 2 - text.x - text.width / 2) < 1
      && document.documentElement.scrollHeight <= innerHeight;
  });
  expect(aligned).toBe(true);
  await page.evaluate(() => window.__releaseGateway());
  await expect(page.locator("#loading-message")).toHaveText("Loading devices");
  await expect(page.locator(".drawbridge-loader")).toBeVisible();
  await expect(loader).toBeInViewport();
  await page.evaluate(() => window.__releaseDevices());
  await expect(loader).toBeHidden({timeout: 1000});
  await expect(page.locator("#controls")).toBeVisible();
});
test("reduced motion displays a still castle during loading", async ({page}) => {
  await page.emulateMedia({reducedMotion: "reduce"});
  await page.addInitScript(() => { window.__scenario = "loading"; });
  await page.goto("/");
  const icon = page.locator(".drawbridge-loader img");
  await expect.poll(() => icon.evaluate(image => image.complete && image.naturalWidth === 128)).toBe(true);
  const firstFrame = await icon.screenshot();
  await page.waitForTimeout(300);
  expect((await icon.screenshot()).equals(firstFrame)).toBe(true);
});
test("failed device loading dismisses the loader and shows the error", async ({page}) => {
  await page.addInitScript(() => { window.__scenario = "load-failure"; });
  await page.goto("/");
  await expect(page.locator("#loading-state")).toBeHidden();
  await expect(page.locator("#user-state")).toBeVisible();
  await expect(page.locator("#user-state")).toHaveText("Couldn't load gate access.");
  await expect(page.locator("#controls")).toBeHidden();
});
test("signed-out and unassigned users cannot send commands", async ({page}) => {
  await page.addInitScript(() => { window.__scenario = "signed-out"; });
  await page.goto("/");
  await expect(page.locator("#sign-in")).toBeVisible();
  await expect(page.locator("#controls")).toBeHidden();
  await page.addInitScript(() => { window.__scenario = "unauthorized"; });
  await page.reload();
  await expect(page.locator("#user-state")).toContainText("No gate access");
  await expect(page.locator("#controls")).toBeHidden();
});
test("profile photo opens and dismisses the account menu", async ({page}) => {
  await page.goto("/");
  const menu = page.locator("#account-dropdown");
  await expect(menu).toBeHidden();
  await page.locator("#account-menu-button").click();
  await expect(menu).toBeVisible();
  await expect(page.locator("#refresh")).toBeVisible();
  await expect(page.locator("#rename")).toBeVisible();
  await expect(page.locator("#sign-out")).toBeVisible();
  await page.keyboard.press("Escape");
  await expect(menu).toBeHidden();
  await page.locator("#account-menu-button").click();
  await page.locator("main").click({position: {x: 5, y: 300}});
  await expect(menu).toBeHidden();
});
test("all durations, device selection, double tap prevention, and sign-out", async ({page}) => {
  await page.goto("/");
  await expect(page.locator("#controls")).toBeVisible();
  await expect(page.locator(".castle-icon")).toBeVisible();
  await expect(page.locator("#profile-photo")).toBeVisible();
  await expect(page.locator("#account-dropdown")).toBeHidden();
  await expect(page.locator("#user-state")).toBeHidden();
  await page.locator("#device").selectOption("second-device");
  page.on("dialog", dialog => dialog.accept());
  for (const duration of [60, 900, 3600, 21600, 0]) {
    await page.locator('[data-duration="' + duration + '"]').click();
    await expect(page.locator('[data-duration="60"]')).toBeDisabled();
    await expect(page.locator("#result")).toContainText("accepted by broker");
  }
  const commands = await page.evaluate(() => window.__commands);
  expect(commands.map(c => c.durationSeconds)).toEqual([60, 900, 3600, 21600, 0]);
  expect(commands.every(c => c.deviceId === "second-device" && c.issuedAtMs > 0)).toBeTruthy();
  expect(new Set(commands.map(c => c.requestId)).size).toBe(5);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  expect(await page.evaluate(() => document.documentElement.scrollHeight <= window.innerHeight)).toBeTruthy();
  await page.screenshot({path: "artifacts/drawbridge-" + test.info().project.name + ".png", fullPage: true});
  await page.locator("#account-menu-button").click();
  await page.locator("#sign-out").click();
  await expect(page.locator("#controls")).toBeHidden();
});
test("offline app shell loads and never queues commands", async ({page, context, browserName}) => {
  test.skip(browserName !== "chromium", "Playwright service-worker support is Chromium-only; verify iOS offline launch manually.");
  await page.goto("/");
  await expect(page.locator("#controls")).toBeVisible();
  await page.evaluate(() => navigator.serviceWorker.ready);
  await page.reload();
  await expect.poll(() => page.evaluate(() => !!navigator.serviceWorker.controller)).toBe(true);
  await context.setOffline(true);
  await page.evaluate(() => { window.__beforeReload = true; });
  await page.goto("/index.html");
  expect(await page.evaluate(() => window.__beforeReload)).toBeUndefined();
  await expect(page.locator(".wordmark")).toBeVisible();
  await expect(page.locator("#offline")).toBeVisible();
  await expect(page.locator('[data-duration="60"]')).toBeDisabled();
  await context.setOffline(false);
  await expect(page.locator('[data-duration="60"]')).toBeEnabled();
  expect(await page.evaluate(() => window.__commands || [])).toEqual([]);
});
test("offline controls disable immediately and reconnect never sends a command", async ({page, context}) => {
  await page.goto("/");
  await expect(page.locator("#controls")).toBeVisible();
  await context.setOffline(true);
  await expect(page.locator("#offline")).toBeVisible();
  await expect(page.locator('[data-duration="60"]')).toBeDisabled();
  await context.setOffline(false);
  await expect(page.locator('[data-duration="60"]')).toBeEnabled();
  expect(await page.evaluate(() => window.__commands || [])).toEqual([]);
});
test("uncertain delivery is never reported as a successful gate action", async ({page}) => {
  await page.addInitScript(() => { window.__scenario = "failure"; });
  await page.goto("/");
  await page.locator('[data-duration="60"]').click();
  await expect(page.locator("#result")).toContainText("Delivery is uncertain");
  expect(await page.evaluate(() => window.__commands.length)).toBe(1);
});
test("accepted hold displays a persistent expected countdown and elapsed progress", async ({page}) => {
  await page.goto("/");
  await page.locator('[data-duration="900"]').click();
  const button = page.locator('[data-duration="900"]');
  await expect(button).toHaveClass(/hold-active/);
  await expect(page.locator("#hold-countdown")).toHaveText(/14:5\d remaining/);
  const initialProgress = Number(await button.evaluate(element => getComputedStyle(element).getPropertyValue("--hold-progress")));
  expect(initialProgress).toBeGreaterThanOrEqual(0);
  await page.waitForTimeout(1100);
  const laterProgress = Number(await button.evaluate(element => getComputedStyle(element).getPropertyValue("--hold-progress")));
  expect(laterProgress).toBeGreaterThan(initialProgress);
  await page.locator("#account-menu-button").click();
  await page.locator("#refresh").click();
  await expect(page.locator("#hold-countdown")).toHaveText(/remaining/);
  await page.locator('[data-duration="0"]').click();
  await expect(button).not.toHaveClass(/hold-active/);
  await expect(page.locator("#hold-countdown")).toBeHidden();
});
test("edit nickname saves selected gate, survives access refresh, and renders as text", async ({page}) => {
  await page.goto("/");
  await page.locator("#device").selectOption("second-device");
  await page.locator("#account-menu-button").click();
  await page.locator("#rename").click();
  await expect(page.locator("#nickname")).toHaveValue("Driveway");
  await page.locator("#nickname").fill("  <Garden gate>  ");
  await page.locator("#nickname-save").click();
  await expect(page.locator("#result")).toHaveText("Gate nickname saved.");
  await expect(page.locator("#device option:checked")).toHaveText("<Garden gate>");
  await page.locator("#account-menu-button").click();
  await page.locator("#refresh").click();
  await expect(page.locator('#device option[value="second-device"]')).toHaveText("<Garden gate>");
  await expect(page.locator('#device option[value="test-device"]')).toHaveText("Garden gate");
  expect(await page.evaluate(() => window.__commands || [])).toEqual([]);
  await page.locator("#account-menu-button").click();
  await page.locator("#rename").click();
  await page.locator("#nickname").fill("   ");
  await page.locator("#nickname-save").click();
  await expect(page.locator("#nickname-result")).toHaveText("Enter a nickname.");
  await page.locator("#nickname-cancel").click();
  await expect(page.locator("#nickname-form")).toBeHidden();
});
test("failed nickname save preserves the existing name and the draft", async ({page}) => {
  await page.addInitScript(() => { window.__scenario = "failure"; });
  await page.goto("/");
  await page.locator("#account-menu-button").click();
  await page.locator("#rename").click();
  await page.locator("#nickname").fill("Front gate");
  await page.locator("#nickname-save").click();
  await expect(page.locator("#nickname-result")).toContainText("Couldn't save");
  await expect(page.locator("#nickname")).toHaveValue("Front gate");
  await expect(page.locator("#device option:checked")).toHaveText("Garden gate");
});
test("only administrators see Administration in the profile dropdown", async ({page}) => {
  await page.goto("/");
  await page.locator("#account-menu-button").click();
  await expect(page.locator("#admin-open")).toBeHidden();
  await page.addInitScript(() => { window.__scenario = "admin"; });
  await page.reload();
  await page.locator("#account-menu-button").click();
  await expect(page.locator("#admin-open")).toBeVisible();
});
test("admin manages roles and firmware on mobile without publishing holds", async ({page, context}) => {
  await page.addInitScript(() => { window.__scenario = "admin"; });
  page.on("dialog", dialog => dialog.accept());
  await page.goto("/");
  await page.locator("#account-menu-button").click();
  await page.locator("#admin-open").click();
  await expect(page.locator("#admin-view")).toBeVisible();
  await expect(page.locator("#controls")).toBeHidden();
  await expect(page.getByRole("tab", {name: "Admins", exact: true})).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("#admin-panel-firmware")).toBeHidden();
  await expect(page.locator("#admin-back")).toHaveCount(0);
  await expect(page.locator("#admin-people")).toContainText("nick.stielau@gmail.com");
  await page.locator("#admin-email").fill("jess@example.test");
  await page.getByRole("button", {name: "Add administrator", exact: true}).click();
  await expect(page.locator("#admin-people")).toContainText("jess@example.test");
  await page.getByRole("button", {name: "Remove", exact: true}).click();
  await expect(page.locator("#admin-people")).not.toContainText("jess@example.test");
  const firmwareTab = page.getByRole("tab", {name: "Device Firmware", exact: true});
  await page.getByRole("tab", {name: "Admins", exact: true}).focus();
  await page.keyboard.press("ArrowRight");
  await expect(firmwareTab).toBeFocused();
  await expect(firmwareTab).toHaveAttribute("aria-selected", "true");
  await expect(page.locator("#admin-panel-people")).toBeHidden();
  await page.getByRole("button", {name: "Refresh administration", exact: true}).click();
  await expect(page.getByRole("button", {name: "Refresh administration", exact: true})).toBeEnabled();
  await expect(firmwareTab).toHaveAttribute("aria-selected", "true");
  await page.getByLabel("Firmware release for Garden gate").selectOption("1.0.0");
  await page.getByRole("button", {name: "Assign release", exact: true}).click();
  await expect(page.locator("#admin-devices")).toContainText("Target: 1.0.0");
  await page.getByRole("button", {name: "Pause updates", exact: true}).click();
  await expect(page.locator("#admin-devices")).toContainText("Automatic updates paused.");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({path: "artifacts/admin-" + test.info().project.name + ".png", fullPage: true});
  await context.setOffline(true);
  await expect(page.getByRole("button", {name: "Assign release", exact: true})).toBeDisabled();
  await page.getByRole("tab", {name: "Admins", exact: true}).click();
  await expect(page.getByRole("button", {name: "Add administrator", exact: true})).toBeDisabled();
  await context.setOffline(false);
  expect(await page.evaluate(() => window.__commands || [])).toEqual([]);
  await page.getByRole("link", {name: "Drawbridge home"}).click();
  await expect(page.locator("#controls")).toBeVisible();
  expect(await page.evaluate(() => window.__commands || [])).toEqual([]);
  await page.locator("#account-menu-button").click();
  await page.locator("#sign-out").click();
  await expect(page.locator("#admin-view")).toBeHidden();
  await expect(page.locator("#admin-people")).toBeEmpty();
});
test("revoked role cannot open admin data even if its menu was previously visible", async ({page}) => {
  await page.addInitScript(() => { window.__scenario = "admin-revoked"; });
  await page.goto("/");
  await page.locator("#account-menu-button").click();
  await page.locator("#admin-open").click();
  await expect(page.locator("#admin-view")).toBeHidden();
  await expect(page.locator("#result")).toContainText("Administrator access unavailable");
});

test("firmware shows independently reported base and app versions, including legacy boards", async ({page}) => {
  await page.addInitScript(() => {
    window.__scenario = "admin";
    window.__firmwareReport = {version: "1.0.9", base_version: "1.0.1", state: "current", atMs: Date.now()};
  });
  await page.goto("/");
  await page.locator("#account-menu-button").click();
  await page.locator("#admin-open").click();
  await page.getByRole("tab", {name: "Device Firmware", exact: true}).click();
  await expect(page.locator("#admin-devices")).toContainText("App 1.0.9 · Base 1.0.1");
  await page.evaluate(() => { delete window.__firmwareReport.base_version; });
  await page.getByRole("button", {name: "Refresh administration"}).click();
  await expect(page.locator("#admin-devices")).toContainText("App 1.0.9 · Base not reported");
});
